import type { ApprovalProfile } from "./types";

export const approvalProfiles: ApprovalProfile[] = [
  {
    id: "prv_8f21bali",
    userId: "usr_khanhlinh",
    businessName: "Viet Horizon Travel",
    businessType: "tour",
    taxCode: "0312456789",
    licenseUrl: "https://example.com/giay-phep-lu-hanh.pdf",
    website: "https://viethorizon.vn",
    address: "28 Nguyễn Thị Minh Khai, Quận 1, TP. Hồ Chí Minh",
    description:
      "Đơn vị tổ chức tour trải nghiệm bản địa, tour trekking và hành trình theo nhóm nhỏ tại Việt Nam.",
    photoUrl: "/hero.jpg",
    approvalStatus: "pending",
    rejectionReason: null,
    createdAt: "2026-09-26T03:20:00.000Z",
    updatedAt: "2026-09-26T03:20:00.000Z",
    user: {
      fullname: "Nguyễn Khánh Linh",
      email: "linh@viethorizon.vn",
      phone: "090 123 4567",
    },
  },
  {
    id: "prv_7c14hotel",
    userId: "usr_minhquan",
    businessName: "Mây Lang Thang Retreat",
    businessType: "hotel",
    taxCode: "5801493210",
    licenseUrl: "https://example.com/dang-ky-kinh-doanh.pdf",
    website: "https://maylangthang.vn",
    address: "12 Trần Hưng Đạo, Phường 10, Đà Lạt, Lâm Đồng",
    description:
      "Khu lưu trú boutique hướng đến trải nghiệm nghỉ dưỡng gần thiên nhiên và văn hóa địa phương.",
    photoUrl: null,
    approvalStatus: "pending",
    rejectionReason: null,
    createdAt: "2026-09-25T08:45:00.000Z",
    updatedAt: "2026-09-25T09:10:00.000Z",
    user: {
      fullname: "Trần Minh Quân",
      email: "quan@maylangthang.vn",
      phone: "091 882 0931",
    },
  },
  {
    id: "prv_3a09food",
    userId: "usr_thuyanh",
    businessName: "Bếp Nhà Ven Sông",
    businessType: "restaurant",
    taxCode: "0402198845",
    licenseUrl: "https://example.com/gpkd-bep-nha.pdf",
    website: null,
    address: "86 Bạch Đằng, Hải Châu, Đà Nẵng",
    description:
      "Nhà hàng món Việt hiện đại, sử dụng nguyên liệu theo mùa từ các nông trại và làng nghề miền Trung.",
    photoUrl: null,
    approvalStatus: "pending",
    rejectionReason: null,
    createdAt: "2026-09-24T07:15:00.000Z",
    updatedAt: "2026-09-24T07:15:00.000Z",
    user: {
      fullname: "Lê Thùy Anh",
      email: "anh@bepnhavensong.vn",
      phone: "093 512 7088",
    },
  },
  {
    id: "prv_6d81tour",
    userId: "usr_hoangan",
    businessName: "Highland Loop Adventure",
    businessType: "tour",
    taxCode: "5100497812",
    licenseUrl: "https://example.com/giay-phep-highland.pdf",
    website: "https://highlandloop.vn",
    address: "19 Nguyễn Trãi, TP. Hà Giang, Hà Giang",
    description:
      "Tour xe máy và khám phá cao nguyên đá có hướng dẫn viên địa phương, ưu tiên du lịch có trách nhiệm.",
    photoUrl: null,
    approvalStatus: "approved",
    rejectionReason: null,
    createdAt: "2026-09-22T02:30:00.000Z",
    updatedAt: "2026-09-23T04:12:00.000Z",
    user: {
      fullname: "Vũ Hoàng An",
      email: "an@highlandloop.vn",
      phone: "097 311 2244",
    },
  },
  {
    id: "prv_1e72stay",
    userId: "usr_baotran",
    businessName: "An Lam Riverside Retreat",
    businessType: "hotel",
    taxCode: "3702119900",
    licenseUrl: null,
    website: "https://anlamretreat.vn",
    address: "21/4 Ấp Trung, Thuận An, Bình Dương",
    description:
      "Không gian nghỉ dưỡng ven sông dành cho gia đình và nhóm nhỏ, cách trung tâm thành phố 30 phút.",
    photoUrl: null,
    approvalStatus: "rejected",
    rejectionReason:
      "Hồ sơ chưa đính kèm giấy phép đăng ký kinh doanh hợp lệ.",
    createdAt: "2026-09-20T10:05:00.000Z",
    updatedAt: "2026-09-21T06:40:00.000Z",
    user: {
      fullname: "Phạm Bảo Trân",
      email: "tran@anlamretreat.vn",
      phone: "098 220 1188",
    },
  },
  {
    id: "prv_9b43dine",
    userId: "usr_quochuy",
    businessName: "Mộc Table & Garden",
    businessType: "restaurant",
    taxCode: "0109754321",
    licenseUrl: "https://example.com/gpkd-moc-table.pdf",
    website: "https://moctable.vn",
    address: "15 Từ Hoa, Tây Hồ, Hà Nội",
    description:
      "Nhà hàng sân vườn phục vụ thực đơn Việt Nam đương đại và trải nghiệm dùng bữa riêng tư.",
    photoUrl: null,
    approvalStatus: "approved",
    rejectionReason: null,
    createdAt: "2026-09-18T04:25:00.000Z",
    updatedAt: "2026-09-19T05:10:00.000Z",
    user: {
      fullname: "Đỗ Quốc Huy",
      email: "huy@moctable.vn",
      phone: "096 408 1515",
    },
  },
];
